[project]
name = "cv_spring24"
authors = [
  { name = "yufan", email = "yufan.fong@gmail.com" },
]
readme = "README.md"
requires-python = ">=3.11"

[tool.ruff]
line-length = 80
ignore = ["F403","E741"]
